AWSTemplateFormatVersion: 2010-09-09
Description: Udacity Labs - This template deploys a VPC
Resources:
  UdacityVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Udacity Labs VPC
